# Generated by Django 5.0.1 on 2026-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
