# Generated by Django 5.0.1 on 2026-03-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomization',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_frames/'),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plaques.dimension'),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='fastening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plaques.fastening'),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plaques.material'),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='thickness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plaques.thickness'),
        ),
        migrations.AlterField(
            model_name='productcustomization',
            name='text_value',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
