# Generated by Django 5.0.1 on 2026-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0003_productcustomization_base_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustomization',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
