# Generated by Django 5.0.1 on 2026-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0004_alter_productcustomization_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomization',
            name='portrait_image',
            field=models.ImageField(blank=True, null=True, upload_to='portrait_dummy/'),
        ),
    ]
