# Generated by Django 5.0.1 on 2026-03-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0005_productcustomization_portrait_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomization',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plaques.plaqueshape'),
        ),
    ]
