# Generated by Django 5.0.1 on 2026-03-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0006_productcustomization_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcustomization',
            name='fastening',
        ),
        migrations.RemoveField(
            model_name='productcustomization',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productcustomization',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='productcustomization',
            name='thickness',
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='fastening',
            field=models.ManyToManyField(blank=True, to='plaques.fastening'),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='material',
            field=models.ManyToManyField(blank=True, to='plaques.material'),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='shape',
            field=models.ManyToManyField(blank=True, to='plaques.plaqueshape'),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='thickness',
            field=models.ManyToManyField(blank=True, to='plaques.thickness'),
        ),
    ]
