# Generated by Django 5.0.6 on 2026-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0007_remove_productcustomization_fastening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
