# Generated by Django 5.0.6 on 2026-03-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0008_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='collections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
