# Generated by Django 5.0.6 on 2026-03-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0009_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover_image',
            field=models.ImageField(upload_to='admin_collection/'),
        ),
    ]
