# Generated by Django 5.0.6 on 2026-03-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0010_alter_collection_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
