# Generated by Django 5.0.6 on 2026-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0012_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomization',
            name='mask_shape',
            field=models.CharField(choices=[('square', 'Square'), ('circle', 'Circle'), ('heart', 'Heart'), ('oval', 'Oval')], default='square', max_length=20),
        ),
    ]
