# Generated by Django 5.0.6 on 2026-05-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0014_productcustomization_base_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustomization',
            name='base_shape',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcustomization',
            name='mask_shape',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='TextZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('w', models.FloatField(default=100)),
                ('h', models.FloatField(default=40)),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaques.productcustomization')),
            ],
        ),
    ]
